name: Build

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: build and push docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          FIREBASE_SERVICE_ACCOUNT: ${{ vars.FIREBASE_SERVICE_ACCOUNT }}
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          BASE_URL: ${{ vars.BASE_URL }}
          FIREBASE_WEB_CONFIG: ${{ vars.FIREBASE_WEB_CONFIG }}
          GOOGLE_CLOUD_PROJECT: ${{ vars.GOOGLE_CLOUD_PROJECT }}
          CLOUD_TASKS_QUEUE: ${{ vars.CLOUD_TASKS_QUEUE }}
          GOOGLE_CLOUD_LOCATION: ${{ vars.GOOGLE_CLOUD_LOCATION }}
          API_KEY: ${{ vars.API_KEY }}
        run: |
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev
          docker build . -t southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/student-calendar/backend:latest --build-arg FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT --build-arg DATABASE_URL=$DATABASE_URL --build-arg BASE_URL=$BASE_URL --build-arg GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT --build-arg CLOUD_TASKS_QUEUE=$CLOUD_TASKS_QUEUE --build-arg GOOGLE_CLOUD_LOCATION=$GOOGLE_CLOUD_LOCATION --build-arg API_KEY=$API_KEY
          docker push southamerica-east1-docker.pkg.dev/$GOOGLE_PROJECT/student-calendar/backend:latest
